version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - run:
          name: Basic-setup
          command: |
            sudo apt-get update
            sudo apt-get install apache2
            sudo apt-get install libapache2-mod-wsgi-py3
            sudo apt-get install python3-pip
            sudo pip install flask
            sudo apt install git
#           git config --global user.name "hari"
#           git config --global user.email hariprasadp@qburst.com

      - run:
          name: Flask-app-file
          command: |
            git clone git@github.com:Haripofficial/flaskapp.git
            sudo ln -sT ~/flaskapp /var/www/html/flaskapp
            sudo mv /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf.bak
            sudo mv default.conf /etc/apache2/sites-available/
            sudo service apache2 restart
            ip addr




              